Ch configure eslint 167313388
andela/codepirates-ah-backend pull request #2
Opened 2019-07-30 12:45 UTC by salviosage

#### What does this PR do?

- have Eslint configured in a codebase

#### Description of Task to be completed?

- add Eslint dev dependencies 

- creating .eslintrc file 

- configure eslint  to extends Airbnb-base and add other configurations as stated on [pt story](https://www.pivotaltracker.com/story/show/167313388)

#### How should this be manually tested?

- after cloning a repo  cd to your repo code base and type the command `npm install ` 

- after then you are ready to test 
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
[#167313388](https://www.pivotaltracker.com/story/show/167313388)
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/38810299/62130131-a2788c00-b2d8-11e9-918b-11e2f00d80f3.png)
![image](https://user-images.githubusercontent.com/38810299/62130144-a99f9a00-b2d8-11e9-91a1-745dea24d43f.png)

#### Questions:

2019-07-30 13:45 UTC, Mnickii approved these changes
LGTM

2019-07-30 14:00 UTC, nshutijonathan approved these changes
It looks good to me

2019-07-30 14:00 UTC, nshutijonathan commented on .eslintrc.js
> +  "valid-jsdoc": ["error", {
They are some rules that we have to sync and explain for us what do they do

2019-07-30 16:00 UTC, minega25 approved these changes

2019-07-30 16:12 UTC, nkalyesubula requested changes
Could you please transform the es5 code in .eslintrc.js to es6 code

2019-07-30 16:18 UTC, Mnickii commented on .eslintrc.js
> +};
Add a new line here

2019-07-30 16:19 UTC, Mnickii commented
@nkalyesubula I don't think that's absolutely necessary as it's a config file.

2019-07-30 16:39 UTC, nkalyesubula approved these changes

2019-07-30 18:55 UTC, Anguandia commented
Looks good in to me, good work!

2019-07-30 21:20 UTC, habinezadalvan approved these changes

2019-07-31 07:09 UTC, salviosage commented on .eslintrc.js
> +  "valid-jsdoc": ["error", {
yeah sure

2019-07-31 09:08 UTC, Anguandia commented
Looks fine, please go ahead

2019-07-31 10:00 UTC, merged