#167313414 search functionality
andela/codepirates-ah-backend pull request #32
Opened 2019-08-20 21:26 UTC by habinezadalvan

#### What does this PR do?
- Creates a functionality for search the article.
#### Description of Task to be completed?
- Created the search functionality, and tests
#### How should this be manually tested?
- Clone  the repo
- create .env and add all the environment variables
- git checkout ft-Search-Functionality-1631414
- npm run migration
- npm run seeds
- npm run dev
- use postman and use get route and pass queries in the URL.; valid queries: 'title, keyword, author'
#### Any background context you want to provide?
- none
#### What are the relevant pivotal tracker stories?
[167313414](https://www.pivotaltracker.com/story/show/167313414)
#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2019-08-20 at 23 23 56" src="https://user-images.githubusercontent.com/45101716/63385741-e1fb3b00-c3a1-11e9-8bea-be3db91e5986.png">
![Uploading Screen Shot 2019-08-20 at 23.24.45.png…]()

#### Questions:
none

2019-08-21 08:56 UTC, salviosage requested changes
consider other people's `req queries` whereby I can send offset and limit queries and it cant work the way you are validating queries.

2019-08-21 09:01 UTC, salviosage requested changes

2019-08-21 09:01 UTC, salviosage commented on src/services/article.service.js
> +      return await db.findAll({ where: query });
each query can't work here like limit and offset. have to be out of `where`

2019-08-21 09:01 UTC, salviosage commented on src/middlewares/query.check.js
> +  const validQueries = ['author', 'keyword', 'tag', 'title', 'offset', 'limit'];
consider the other Queries might appear like `newest ` like `weekly` as we had that query in the previous UI we discussed.

2019-08-22 09:10 UTC, habinezadalvan commented
> consider other people's `req queries` whereby I can send offset and limit queries and it cant work the way you are validating queries.

@salviosage I fixed that.

2019-08-22 19:35 UTC, habinezadalvan commented on src/services/article.service.js
> +      return await db.findAll({ where: query });
It has been resolved

2019-08-22 19:48 UTC, salviosage approved these changes
LGTM

2019-08-23 03:23 UTC, Mnickii approved these changes
LGTM

2019-08-23 05:55 UTC, minega25 approved these changes

2019-08-23 06:42 UTC, merged