#167313416 Users should be able to share articles across different channels
andela/codepirates-ah-backend pull request #46
Opened 2019-08-28 15:23 UTC by nkalyesubula

#### What does this PR do?

-  It adds functionality for sharing an article over mail and social media channels

#### Description of Task to be completed?

-  As an authenticated user, I should be able to share articles; both mine and others via email and social media platforms.

#### How should this be manually tested?

- clone the repo and then run **npm run dev**
- In your postman, execute this route **http://localhost:PORT/api/v1/articles/{slug}/share/{channel}**.  Change PORT, slug and channel accordingly. Channels can be facebook, twitter or mail.

#### What are the relevant pivotal tracker stories?
[#167313416](https://www.pivotaltracker.com/story/show/167313416)
#### Screenshots (if appropriate)

#### Questions:

2019-08-28 15:45 UTC, Anguandia submitted a review, later dismissed
Great Noah!!, we'll need some sync and you walk us through the process flow.

2019-08-29 08:09 UTC, habinezadalvan requested changes

2019-08-29 08:09 UTC, habinezadalvan commented on src/controllers/articles.controller.js
> +        status: 404,
Please use util helper

2019-08-29 08:09 UTC, habinezadalvan commented on src/controllers/articles.controller.js
> +        return res.status(200).json({
Please use util helper

2019-08-29 08:09 UTC, habinezadalvan commented on src/controllers/articles.controller.js
> +          status: 200,
Please use util helper

2019-08-29 08:09 UTC, habinezadalvan commented on src/controllers/articles.controller.js
> +          status: 200,
Please use util helper

2019-08-29 08:11 UTC, habinezadalvan requested changes
Please use util helper for every response.

2019-08-29 09:54 UTC, minega25 submitted a review, later dismissed

2019-08-29 09:58 UTC, habinezadalvan submitted a review, later dismissed
awesome work.

2019-08-29 11:27 UTC, Mnickii submitted a review, later dismissed
LGTM

2019-08-29 11:27 UTC, Mnickii commented on src/controllers/articles.controller.js
> +    switch (req.params.channel) {
Nice switch!

2019-08-29 11:31 UTC, merged