#167313389 Integrated HoundCi
andela/codepirates-ah-backend pull request #5
Opened 2019-07-31 09:17 UTC by nshutijonathan

### What does this PR do?
- Configure HoundCi
### Description of Task to be completed?
- added .hound.yml
- Integrated code-pirates backend repo with houndCi services
- added houndCii badge 
### How should this be manually tested?
- open the readme on the repo then click on the HoundCi badge available
### What are the relevant pivotal tracker stories?
[#167313389](https://www.pivotaltracker.com/n/projects/2372121/stories/167313389)
### Screenshots (if appropriate)
<img width="516" alt="Screen Shot 2019-07-31 at 11 15 00" src="https://user-images.githubusercontent.com/16412410/62199848-8d593700-b384-11e9-8c90-9dabd3fbdd21.png">

### Questions:

2019-07-31 10:06 UTC, habinezadalvan approved these changes
I can see that hound is actively connected to the repo.

2019-07-31 10:16 UTC, nkalyesubula requested changes
Nice work. Rebase though so that the file you are referencing in .hound.yml (.eslintrc)may be found

2019-07-31 10:17 UTC, Mnickii commented on .hound.yml
> +  config_file: .eslintrc
Add new line

2019-07-31 11:06 UTC, nshutijonathan commented on .hound.yml
> +  config_file: .eslintrc
> Add new line!
@Mnickii  I have added new line

2019-07-31 12:47 UTC, salviosage approved these changes

2019-07-31 12:48 UTC, minega25 approved these changes

2019-08-01 05:29 UTC, nshutijonathan commented
> Nice work. Rebase though so that the file you are referencing in .hound.yml (.eslintrc)may be found

I have rebased

2019-08-01 06:39 UTC, merged