#169392403: view comments of a particular article
andela/codepirates-ah-backend pull request #70
Opened 2019-10-28 12:13 UTC by habinezadalvan

#### What does this PR do?
- fetches all comments of an article
#### Description of Task to be completed?
- completed the functionality of fetching all comments of a particular article.
#### How should this be manually tested?
- clone the repo
- run:
 **git checkout bg-fix-view-all-comments-of-a-particular-article-169392403**
**npm install**
**npm run dev**
- use postman and do the following:
**Create an article** and user the article slug to comment
Method: POST
url: **http://localhost:3000/api/v1/comments/:articleSlug**
body: {"body": "your comment"}
#### Any background context you want to provide?
none
#### What are the relevant pivotal tracker stories?
[169392403](https://www.pivotaltracker.com/story/show/169392403)
#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2019-10-28 at 14 09 32" src="https://user-images.githubusercontent.com/45101716/67677567-0b7da780-f98d-11e9-9736-019bf8541d60.png">

#### Questions:
none

2019-10-28 12:18 UTC, nshutijonathan requested changes
Seems you did not test your controller but the coverage doesn't drop too much

2019-10-28 12:19 UTC, nshutijonathan submitted a review, later dismissed

2019-10-28 12:36 UTC, minega25 submitted a review, later dismissed

2019-10-30 08:39 UTC, salviosage requested changes
please fix Travis issues

2019-10-30 13:22 UTC, salviosage requested changes
nice work I have left some comment

2019-10-30 13:22 UTC, salviosage commented on src/routes/api/comment/comments.route.js
> +router.delete('/particularArticle/:id', [auth], Comments.deleteCommentOfAnArticle);
I don't think delete have a relationship with delete, so you might still use the current delete comment endpoint

2019-11-03 10:18 UTC, minega25 approved these changes
LGTML

2019-11-03 10:22 UTC, salviosage approved these changes
LGTM

2019-11-03 11:04 UTC, merged